# Netlify configuration for The Pizza Mafia
# Modern Next.js/React, Netlify Functions, and best-practice config

[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  autoLaunch = true

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://thepizzamafia.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# All SPA and catch-all redirects removed for Next.js compatibility
# Netlify Next.js plugin enabled for SSR/ISR and dynamic routes
