# GitHub Actions CI for Pizza Mafia
# Runs lint, prettier, and build checks on every push and PR
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npx prettier --check .
      - name: Run ESLint
        run: npx eslint .
      - name: Build (if Next.js present)
        run: |
          if [ -f package.json ] && grep -q 'next' package.json; then
            npm run build
          fi
